In [1]:
import pandas as pd

In [3]:
input_data = pd.read_csv("../data/features_50_filtered.csv")
input_data.head()

,xco2,month,SWIR_41,SWIR_104,SWIR_106,SWIR_107,SWIR_108,SWIR_110,SWIR_111,SWIR_113,...,CO_SWIR_106_vs_CO2_SWIR_149_ndvi,Infrared_SWIR_108_vs_CO2_SWIR_151_ndvi,Infrared_SWIR_108_vs_CO2_SWIR_154_ndvi,CO_SWIR_106_plus_CO2_SWIR_149_vs_Infrared_SWIR_132_ndvi,VNIR_10_solzen_sin,SWIR_154_view_zen_sin,SWIR_151_view_zen_sin,SWIR_149_view_zen_sin,VNIR_10_view_zen_sin,VNIR_10_relaz_sin
0,421.05835,3,0.19,3.90,1.75,1.06,1.89,5.93,5.73,3.95,...,-0.209932,-0.110588,0.041322,-0.082816,47.745470,0.018099,0.024548,0.027876,0.846267,45.651408
1,418.54514,3,0.18,3.52,1.52,0.98,1.85,5.26,5.29,3.63,...,-0.216495,-0.065657,0.174603,-0.087059,52.880558,0.013587,0.022053,0.024666,0.941812,50.674821
2,413.64883,3,0.09,4.83,2.15,1.45,2.00,7.27,6.88,4.80,...,-0.202226,-0.236641,-0.022005,-0.075472,45.416079,0.021949,0.034027,0.034027,0.812762,43.617856
3,412.05887,3,0.35,5.02,2.14,1.41,2.51,7.58,6.87,4.96,...,-0.193974,-0.068646,0.138322,-0.064317,55.310521,0.020050,0.030391,0.033451,0.994575,53.236453
4,434.43000,3,0.18,4.41,2.10,1.39,2.24,6.71,6.35,4.31,...,-0.210526,-0.123288,0.020501,-0.048301,50.117381,0.022797,0.030431,0.034142,0.905512,48.341690

In [9]:
pretrain_data = input_data.iloc[:, 2:].copy()
pretrain_data.columns = [f"X_{i}" for i in range(len(pretrain_data.columns))]
pretrain_data.to_csv("../data/pretrain.csv", index=False)
pretrain_data.head()

,X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,...,X_36,X_37,X_38,X_39,X_40,X_41,X_42,X_43,X_44,X_45
0,0.19,3.90,1.75,1.06,1.89,5.93,5.73,3.95,4.25,2.68,...,-0.209932,-0.110588,0.041322,-0.082816,47.745470,0.018099,0.024548,0.027876,0.846267,45.651408
1,0.18,3.52,1.52,0.98,1.85,5.26,5.29,3.63,3.78,2.36,...,-0.216495,-0.065657,0.174603,-0.087059,52.880558,0.013587,0.022053,0.024666,0.941812,50.674821
2,0.09,4.83,2.15,1.45,2.00,7.27,6.88,4.80,5.16,3.24,...,-0.202226,-0.236641,-0.022005,-0.075472,45.416079,0.021949,0.034027,0.034027,0.812762,43.617856
3,0.35,5.02,2.14,1.41,2.51,7.58,6.87,4.96,5.24,3.17,...,-0.193974,-0.068646,0.138322,-0.064317,55.310521,0.020050,0.030391,0.033451,0.994575,53.236453
4,0.18,4.41,2.10,1.39,2.24,6.71,6.35,4.31,4.69,3.22,...,-0.210526,-0.123288,0.020501,-0.048301,50.117381,0.022797,0.030431,0.034142,0.905512,48.341690

In [15]:
train_data = input_data.sample(n=350).copy()
del train_data["month"]
train_data.columns = ["Y"] + [f"X_{i}" for i in range(len(train_data.columns) - 1)]
train_data.to_csv("../data/train.csv", index=False)
train_data.head()

,Y,X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,...,X_36,X_37,X_38,X_39,X_40,X_41,X_42,X_43,X_44,X_45
748070,454.87796,0.07,2.86,1.29,0.86,1.35,4.10,3.67,2.49,2.68,...,-0.134228,-0.123377,0.026616,-0.119645,42.869181,0.204512,0.276411,0.270020,12.173267,60.257371
1048349,452.61688,0.19,2.35,0.86,0.49,0.72,2.74,2.57,1.69,1.71,...,-0.156863,-0.269036,-0.142857,-0.141053,43.653845,0.140772,0.183297,0.173032,8.466850,47.698467
766016,365.78420,0.66,6.14,2.99,1.48,2.71,6.98,6.33,4.31,4.53,...,0.029260,-0.009141,0.117526,-0.005988,40.354178,0.790335,1.019310,1.041469,25.848372,55.262224
485694,448.61716,0.15,1.85,0.55,0.37,0.66,2.06,1.97,1.33,1.45,...,-0.285714,-0.254237,-0.057143,-0.151515,37.391061,0.113192,0.169789,0.151433,7.293261,43.675245
223055,531.58670,0.63,6.37,2.19,1.01,2.13,6.46,5.89,3.93,4.22,...,-0.139489,-0.151394,-0.073913,-0.001961,50.796578,0.008939,0.010459,0.010495,0.384422,99.947832

In [16]:
test_data = input_data.sample(n=150).copy()
del test_data["month"]
test_data.columns = ["Y"] + [f"X_{i}" for i in range(len(test_data.columns) - 1)]
test_data.to_csv("../data/test.csv", index=False)
test_data.head()

,Y,X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,...,X_36,X_37,X_38,X_39,X_40,X_41,X_42,X_43,X_44,X_45
813790,536.37840,0.00,1.38,0.56,0.38,0.61,2.43,2.32,1.56,1.74,...,-0.263158,-0.186667,0.025210,-0.243781,38.030413,0.178028,0.273180,0.294666,20.859926,53.813717
606714,332.59128,0.30,3.16,1.54,0.76,1.46,3.61,3.26,2.38,2.49,...,-0.072289,-0.095975,-0.070064,0.004539,35.848576,0.403846,0.425480,0.427884,12.639413,45.285798
164155,423.19644,0.03,1.63,0.53,0.41,0.68,1.97,1.86,1.38,1.47,...,-0.298013,-0.170732,-0.042254,-0.093093,37.185186,0.156361,0.202846,0.207072,11.443905,46.398816
513316,538.33936,0.00,0.65,0.29,0.23,0.36,1.40,1.32,0.88,1.08,...,-0.256410,-0.100000,0.241379,-0.333333,29.424543,0.081058,0.162116,0.180539,19.383957,45.379859
36920,509.03778,0.07,2.37,0.93,0.59,0.94,3.05,2.85,1.99,2.12,...,-0.225000,-0.232653,-0.069307,-0.075145,44.489664,0.077709,0.108648,0.105770,5.400042,48.315703